.github/workflows/ci.yml
=> removed usage of secretes in CI

CedarJava/CHANGELOG.md
=> Add CHANGELOG.md

.github/workflows/publish_release.yml, .github/workflows/publish_release_reusable.yml, CedarJava/.gitignore, CedarJava/gradle.properties
*Issue #, if available:* 18
Some prereqs for maven release. 
=> Some prereqs for maven release

.github/workflows/publish_release_reusable.yml
Build libraries for Mac, Linux and Windows
=> Build libraries for Mac, Linux and Windows

CedarJava/build.gradle, CedarJava/config.sh, CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java, CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java, CedarJavaFFI/Cargo.toml, CedarJavaFFI/src/interface.rs
Preparation for maven release. Make CedarJavaFFI pull cedar from crates.io. Make relevant changes to testing.
=> maven release prep

CedarJava/src/main/java/com/cedarpolicy/SliceJsonSerializer.java, CedarJava/src/main/java/com/cedarpolicy/model/slice/BasicSlice.java, CedarJava/src/main/java/com/cedarpolicy/model/slice/Entity.java, CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java, CedarJava/src/test/java/com/cedarpolicy/pbt/ActionGen.java, CedarJava/src/test/java/com/cedarpolicy/pbt/ParserTest.java
*Issue #, if available:* None
Rename `Euid` to `EUID` for consitency. 
=> Rename Euid to EUID

CedarJavaFFI/Cargo.toml
Don't assume local repo with cedar-policy
=> Don't assume local repo with cedar-policy

.github/workflows/ci.yml, CedarJava/build.gradle, CedarJava/config.sh, CedarJava/src/main/java/com/cedarpolicy/model/exception/DeserializationRecursionDepthException.java, CedarJava/src/main/java/com/cedarpolicy/serializer/ValueCedarDeserializer.java, CedarJava/src/test/java/com/cedarpolicy/JSONTests.java
Catch StackOverflowException during deserialization. A stack overflow is treated as an input constraint violation (i.e., the same sort of error as an input string that is too long)
=> catch StackOverflowException in deserialization

.github/workflows/ci.yml, CedarJava/build.gradle, CedarJava/config.sh, CedarJava/src/main/java/com/cedarpolicy/model/exception/DeserializationRecursionDepthException.java, CedarJava/src/main/java/com/cedarpolicy/serializer/ValueCedarDeserializer.java, CedarJava/src/test/java/com/cedarpolicy/JSONTests.java
=> catch StackOverflowException in deserialization (#46)

CedarJava/config.sh, CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java, CedarJavaFFI/Cargo.toml, CedarJavaFFI/src/interface.rs
Updates to match [cedar#334](https://github.com/cedar-policy/cedar/pull/334).
=> bump versions to 3.0

CedarJava/build.gradle
=> Update guava dep

CedarJava/build.gradle, CedarJava/config.sh
=> make findbugs a compileOnly dependency (#56)

README.md
add TLDR instructions to top-level README
=> add TLDR instructions to top-level README

.github/workflows/ci.yml, CedarJava/build.gradle, CedarJava/config.sh, CedarJava/suppressions.xml
=> 2.3.x dep check

CedarJavaFFI/Cargo.toml
=> pull Cedar 2.4

CedarJavaFFI/Cargo.toml
=> pull Cedar 2.3

CedarJavaFFI/Cargo.toml
=> pull Cedar 2.0

.github/workflows/publish_release_reusable.yml
Not sure what this workflow is used for, but this fixes a YAML syntax issue in it.
Fix #84 
=> Fix yaml in workflow

CedarJava/src/main/java/com/cedarpolicy/model/exception/DeserializationRecursionDepthException.java, CedarJava/src/main/java/com/cedarpolicy/model/slice/BasicSlice.java, CedarJava/src/main/java/com/cedarpolicy/serializer/ValueCedarDeserializer.java, CedarJava/src/main/java/com/cedarpolicy/serializer/package-info.java, CedarJava/src/test/java/com/cedarpolicy/EntityIdTests.java, CedarJava/src/test/java/com/cedarpolicy/EntityTypeNameTests.java, CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java, CedarJava/src/test/java/com/cedarpolicy/ValidationTests.java, CedarJava/src/test/java/com/cedarpolicy/pbt/EntityGen.java
=> Resolve some warnings highlighted by vscode

.github/dependabot.yml
It seems to have worked well [in the `cedar` repo](https://github.com/cedar-policy/cedar/pull/662).
=> Use dependabot for automatic dependency updates

.github/workflows/ci.yml, CedarJava/config.sh, CedarJavaFFI/Cargo.toml
=> Update build process of CedarJavaFFI

CedarJava/src/main/java/com/cedarpolicy/model/ValidationResponse.java, CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java, CedarJava/src/test/java/com/cedarpolicy/ValidationTests.java
Update ValidationResponse for new interface from https://github.com/cedar-policy/cedar/pull/740
=> Update ValidationResponse for new interface

THIRD_PARTY_LICENSES.txt
Add third party licenses for shared library
=> Add third party licenses for shared library

CedarJava/build.gradle
=> gradle publish 3.1.x

CedarJava/src/main/java/com/cedarpolicy/model/PartialAuthorizationResponse.java, CedarJava/src/test/java/com/cedarpolicy/AuthTests.java, CedarJava/src/test/java/com/cedarpolicy/JSONTests.java
=> Updates for cedar-policy/#714

CedarJava/build.gradle
=> fix gradle publish action

.github/workflows/ci.yml, .github/workflows/run_cedar_java_reusable.yml, CedarJava/build.gradle, CedarJava/src/test/java/com/cedarpolicy/ValidationTests.java, CedarJavaFFI/Cargo.toml, CedarJavaFFI/src/answer.rs, CedarJavaFFI/src/interface.rs, CedarJavaFFI/src/interface_result.rs, CedarJavaFFI/src/lib.rs
cedar-policy/cedar#794
Also a couple unrelated nits.
CedarJavaFFI tests are currently failing due to #126.
=> update for cedar#794

CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java, CedarJava/src/main/java/com/cedarpolicy/SliceJsonSerializer.java, CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationRequest.java, CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationResponse.java, CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationSuccessResponse.java, CedarJava/src/main/java/com/cedarpolicy/model/PartialAuthorizationRequest.java, CedarJava/src/main/java/com/cedarpolicy/model/slice/BasicSlice.java, CedarJava/src/main/java/com/cedarpolicy/model/slice/TemplateInstantiation.java, CedarJava/src/test/java/com/cedarpolicy/AuthTests.java, CedarJava/src/test/java/com/cedarpolicy/JSONTests.java, CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java, CedarJava/src/test/java/com/cedarpolicy/pbt/IntegrationTests.java, CedarJavaFFI/src/interface.rs
cedar-policy/cedar#814
CI will probably fail until cedar-policy/cedar#819 is merged.
=> update for cedar#814

CedarJava/README.md, CedarJava/src/main/java/com/cedarpolicy/model/SourceLocation.java, CedarJava/src/main/java/com/cedarpolicy/model/ValidationResponse.java
N/A
Cedar policy #824 (https://github.com/cedar-policy/cedar/pull/824) broke the JSON interface, reflecting that here
=> Updating json to match cedar-policy/#824

CedarJava/src/main/java/com/cedarpolicy/model/ValidationResponse.java
=> update for cedar#831

CedarJavaFFI/Cargo.toml
add license and description to Cargo file
=> add license and description to Cargo file

CedarJava/src/test/java/com/cedarpolicy/pbt/Utils.java
Add 'is' to reserved words for property tests
=> Add 'is' to reserved words for property tests

CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java, CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationRequest.java, CedarJava/src/main/java/com/cedarpolicy/model/PartialAuthorizationRequest.java, CedarJava/src/test/java/com/cedarpolicy/JSONTests.java, CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java, CedarJava/src/test/java/com/cedarpolicy/pbt/IntegrationTests.java, CedarJavaFFI/src/tests.rs
N/A
Removes unspecified and adjusts APIs
=> Implement RFC55

CedarJava/src/main/java/com/cedarpolicy/model/schema/Schema.java, CedarJava/src/main/java/com/cedarpolicy/serializer/SchemaSerializer.java, CedarJava/src/test/java/com/cedarpolicy/SchemaTests.java, CedarJava/src/test/java/com/cedarpolicy/TestUtil.java, CedarJavaFFI/src/interface.rs
=> Changes needed by cedar-policy/cedar#1114

.github/workflows/ci.yml, CedarJava/build.gradle, CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java, CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java, CedarJavaFFI/Cargo.toml, CedarJavaFFI/src/interface.rs
Backport #182. Also bumps all relevant versions to 3.3.
=> backport #182

CedarJava/src/main/java/com/cedarpolicy/formatter/PolicyFormatter.java, CedarJava/src/test/java/com/cedarpolicy/PolicyFormatterTests.java, CedarJava/src/test/resources/formatted_policy.cedar, CedarJava/src/test/resources/unformatted_policy.cedar, CedarJavaFFI/Cargo.toml, CedarJavaFFI/src/interface.rs, configure_ci_build.sh
=> Add support for cedar-policy-formatter (#180)

CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java
Remove test case that shouldn't pass
=> Remove test that shouldn't pass

.github/workflows/run_cedar_java_reusable.yml
Downgrade Rust toolchain to 1.80
=> Fix CI build

.github/workflows/run_cedar_java_reusable.yml
=> Cherry-pick #198

.github/workflows/ci.yml, .github/workflows/run_cedar_java_reusable.yml, CedarJava/build.gradle, CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java, CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java, CedarJavaFFI/Cargo.toml, CedarJavaFFI/src/interface.rs
Bumps versions to 3.4 and backports #198.
=> Prep 3.4.x branch and backport #198

CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java, CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java, CedarJava/src/main/java/com/cedarpolicy/CedarJson.java, CedarJava/src/main/java/com/cedarpolicy/model/EntityValidationRequest.java, CedarJava/src/main/java/com/cedarpolicy/serializer/EntitySerializer.java, CedarJava/src/test/java/com/cedarpolicy/EntityValidationTests.java, CedarJava/src/test/resources/role_schema.json, CedarJavaFFI/src/interface.rs
Cherry-pick: https://github.com/cedar-policy/cedar-java/pull/202
=> Cherry-pick #202

.github/workflows/ci.yml, .github/workflows/publish_release.yml, .github/workflows/publish_release_reusable.yml, CedarJava/config.sh, CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java, CedarJavaFFI/Cargo.toml, CedarJavaFFI/src/interface.rs
Bump versions on the 2.5.x branch. Trying to get upstream CI working for https://github.com/cedar-policy/cedar/pull/1200.
=> set up 2.5.x branch

CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java, CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java, CedarJava/src/main/java/com/cedarpolicy/model/EntityValidationRequest.java, CedarJava/src/test/java/com/cedarpolicy/EntityValidationTests.java, CedarJava/src/test/resources/role_schema.json, CedarJavaFFI/src/interface.rs, CedarJavaFFI/src/tests.rs
Issue #, if available:
Description of changes:
This PR adds support for cedar-entity-validation.
- Add entity validation in rust
- Add entity validation in java
- Add unit test in java and rust.
Similar to this: https://github.com/cedar-policy/cedar-java/pull/202
=> Add support for cedar entities validation.

CedarJava/build.gradle, CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java, CedarJavaFFI/Cargo.toml
=> Use the release branch of Cedar

CedarJavaFFI/Cargo.toml, CedarJavaFFI/src/interface.rs
=> Bump version to 3.4.1

.github/workflows/ci.yml
=> Cherry-pick #216 to release 4.0.x

.github/workflows/run_cedar_java_reusable.yml, CedarJava/build.gradle
This should allow us to use Rust 1.81.
=> bump zigbuild version

CedarJava/build.gradle, CedarJava/src/main/java/com/cedarpolicy/model/SourceLocation.java, CedarJava/src/main/java/com/cedarpolicy/model/policy/Policy.java, CedarJava/src/main/java/com/cedarpolicy/serializer/JsonEUID.java, CedarJava/src/main/java/com/cedarpolicy/serializer/ValueDeserializer.java, CedarJava/src/main/java/com/cedarpolicy/value/EntityIdentifier.java, CedarJava/src/main/java/com/cedarpolicy/value/EntityTypeName.java, CedarJava/src/main/java/com/cedarpolicy/value/EntityUID.java
Currently it's not that painful to maintain compatibility with JDK8 in non-test classes.
=> JDK8 compatibility for non-test classes

CedarJavaFFI/Cargo.toml
=> Bumping version numbers

CedarJava/build.gradle
=> Bumping versions

CedarJava/src/main/java/com/cedarpolicy/model/entity/Entity.java, CedarJava/src/main/java/com/cedarpolicy/serializer/EntitySerializer.java, CedarJava/src/test/java/com/cedarpolicy/EntityValidationTests.java, CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java
https://github.com/cedar-policy/cedar-java/pull/238
Changes done in `release/4.2.x` applied for `main`
Did a `git diff HEAD~1 > tags.patch` then did `git apply tags.patch` in my `main` fork
=> Adding tags support

.github/workflows/run_cedar_java_reusable.yml
=> Let CI use Rust 1.81

CedarJava/src/main/java/com/cedarpolicy/serializer/ValueDeserializer.java, CedarJava/src/main/java/com/cedarpolicy/serializer/ValueSerializer.java, CedarJava/src/main/java/com/cedarpolicy/value/Unknown.java, CedarJava/src/test/java/com/cedarpolicy/AuthTests.java, CedarJava/src/test/java/com/cedarpolicy/JSONTests.java
=> Cherry-pick #259

CedarJava/build.gradle
=> Update Rust to 1.83

CedarJava/build.gradle, CedarJavaFFI/Cargo.toml
Preparing for the 4.2.3 release to Maven.
Updating the version numbers.
=> Bumping the version number to 4.2.3

CedarJava/src/main/java/com/cedarpolicy/model/entity/Entity.java, CedarJava/src/main/java/com/cedarpolicy/model/policy/PolicySet.java, CedarJava/src/test/java/com/cedarpolicy/EntityTests.java, CedarJava/src/test/java/com/cedarpolicy/PolicySetTests.java, CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java
Cherry picking #282 
Not bumping version number because we will be adding more updates to 4.2.4
=> Adds getter methods for PolicySet and Entity (#282)

CedarJava/src/test/java/com/cedarpolicy/EntitiesTests.java
=> updates tests to be compatible with older JSONAssert versions (#311)

CedarJava/build.gradle
Matching Cedar version increase in https://github.com/cedar-policy/cedar/pull/1683
=> Bump Rust version to 1.85
