cedar-policy/cedar-java

CedarJava/build.gradle
CedarJava/config.sh
CedarJava/src/main/java/com/cedarpolicy/SliceJsonSerializer.java
CedarJava/src/main/java/com/cedarpolicy/serializer/JsonEUID.java
CedarJava/src/main/java/com/cedarpolicy/serializer/ValueCedarDeserializer.java
CedarJava/src/main/java/com/cedarpolicy/serializer/ValueCedarSerializer.java
CedarJava/src/main/java/com/cedarpolicy/value/EntityUID.java
CedarJava/src/test/java/com/cedarpolicy/JSONTests.java
CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java

https://github.com/cedar-policy/cedar-java/issues/30
Updates to fix the corpus tests. Remove usage of `__expr` escape.

fix corpus tests

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
CedarJava/build.gradle
CedarJavaFFI/Cargo.toml
CedarJavaFFI/README.md
README.md

* Revised text in the toplevel README to indicate that users should use a `release` branch unless they're building the `cedar-policy` crate locally.
* Updated the `Cargo.toml` in `CedarJavaFFI` to point to a local copy of `cedar` rather than the one available on crates.io.
* Updated links in `bug_report.yml` to point to the correct repo.
* Copied `feature_request.yml` from our [`cedar`](https://github.com/cedar-policy/cedar) repo.

Updates to documentation

---

.github/workflows/publish_release_reusable.yml

Simplify the release publishing workflows.
- Get cedar from crates.io
- Don't build CedarJava (temporary)

simplify release publication

---

CedarJavaFFI/src/interface.rs

add parse euid api
Needed to deprecate `__expr` escape in `3.0` (https://github.com/cedar-policy/cedar/pull/333)

add parse euid api

---

CedarJava/build.gradle
CedarJava/config.sh

make findbugs a compileOnly dependency

make findbugs a compileOnly dependency

---

CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java

Fix for [cedar#589](https://github.com/cedar-policy/cedar/pull/589), which updates the integration test format. That PR must be merged before the CI will succeed for this PR.

Fix for cedar#589

---

CedarJava/build.gradle
CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationResponse.java
CedarJava/src/main/java/com/cedarpolicy/model/slice/TemplateInstantiation.java

This pull request reduces the number and scope of dependencies required for the `cedar-java` library.
Changes include the following:
- Removed unused Apache Commons Text
- Removed Google Guava
- Replaced Guava ImmutableList with Collection.unmodifiableList()
- Changed FindBugs annotations library to compileOnly
- Changed Log4j 2 to testImplementation
Apache Commons Text did not have any direct references in Java classes. Log4j 2 is only necessary for test classes, so it should be declared as a test implementation dependency, allowing runtime integrations to provide an SLF4J implementation as needed.
FindBugs provides annotations to suppress FindBugs warnings, but these annotations are not necessary for runtime operation, as Java Virtual …

Reduce implementation dependencies

---

CedarJava/build.gradle
CedarJava/config.sh
CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationResponse.java
CedarJava/src/main/java/com/cedarpolicy/model/slice/TemplateInstantiation.java

This fixes an error caused by conflicting merges. A PR added new code which depended on Guava while another deleted the dependency. 
The commit adds the dependency rather than updating the code to not require the dependency because my understanding is that Guava immutable sets provide better guarantees than Java unmodifiable collections. Specifically, unmodifiable sets hold a reference to the set used in their construction. If a reference is kept to the set used to construct an unmodifiable set, then any mutation to that set is reflected in the unmodifiable set. The Guava immutable set creates a copy.
In any case where we store the set in a field of an object, we should use guava immutable types. When _returning_ a collection, we can use the builtin unmodifiable methods to avoid copying …

Fix build by reinstating Guava dependency

---

CedarJava/config.sh

Instead of using `sed` to replace a specific line number, the script now looks for a pattern describing the line to replace, verifies that the pattern appears exactly once in the file, and then replaces the line with the new contents. If the pattern doesn't appear or appears more than once, the CI will fail immediately. This is an improvement over the previous behavior where a change to the contents of one of the files would cause an incorrect line to be replaced, manifesting as an error somewhere later in the CI processes.

Make `sed` edits in `config.sh` more robust

---

.github/workflows/ci.yml
CedarJava/src/main/java/com/cedarpolicy/model/slice/Entity.java

Fix one error reported by `./gradlew javadoc`. Other workflow tweaks (change names, use same flags for cargo build and test to save a bit of build time)

Add check that javadocs build to CI

---

CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java

No matching issue
Removed superfluous log statement template placeholder that causes an IllegalArgumentException from BasicAuthorizationEngine::call. It appears that the full request log was moved to the subsequent LOG.trace statement, but the corresponding placeholder in this line was not removed. In the latest release available in the MavenCentral repository (2.4.3), this can cause authorization requests to fail if the log level is debug or lower.

Fix log statement (v2.4.x)

---

CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java

No matching issue
Removed superfluous log statement template placeholder that causes an IllegalArgumentException from BasicAuthorizationEngine::call. It appears that the full request log was moved to the subsequent LOG.trace statement, but the corresponding placeholder in this line was not removed. This can cause authorization requests to fail if the log level is debug or lower. This fix is the same as [PR #90 ](https://github.com/cedar-policy/cedar-java/pull/90), but targets the main branch instead of the current MavenCentral release branch.

Update BasicAuthorizationEngine.java to fix logger error

---

CedarJava/config.sh
CedarJavaFFI/Cargo.toml

update for cedar#726 (version numbers)

---

.github/workflows/ci.yml
.gitignore
CedarJava/README.md
CedarJava/build.gradle
CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java
CedarJava/src/main/java/com/cedarpolicy/loader/LibraryLoader.java
CedarJava/src/main/java/com/cedarpolicy/model/schema/Schema.java
CedarJava/src/main/java/com/cedarpolicy/model/slice/Policy.java
CedarJava/src/main/java/com/cedarpolicy/serializer/JsonEUID.java
CedarJava/src/main/java/com/cedarpolicy/value/Decimal.java
CedarJava/src/main/java/com/cedarpolicy/value/EntityIdentifier.java
CedarJava/src/main/java/com/cedarpolicy/value/EntityTypeName.java
CedarJava/src/main/java/com/cedarpolicy/value/EntityUID.java
CedarJava/src/main/java/com/cedarpolicy/value/IpAddress.java
CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java

Issue #28
This pull request incorporates both code and build changes to provide an uber JAR that bundles the native Cedar Foreign Function Interface libraries required for JNI operations.
The code changes consists of a new `LibraryLoader` class that introduces a shared method named `loadLibrary()` to handle native library loading. The `LibraryLoader.loadLibrary()` call replaces all instances of `System.load()`, maintaining the existing option to load the native library from a path specified in the `CEDAR_JAVA_FFI_LIB` environment variable.
When the `CEDAR_JAVA_FFI_LIB` environment variable in not specified, `LibraryLoader.loadLibrary()` delegates to the [Java Native Environment](https://github.com/fizzed/jne) `JNE.loadLibrary()` method, …

Add Gradle tasks for bundling native libraries

---

.github/workflows/ci.yml
CedarJava/README.md
CedarJava/build.gradle
CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java
README.md

This pull request updates the Gradle configuration to download the `main` branch of the Cedar repository, incorporating integration testing in the standard build. The [gradle-download-task](https://github.com/michel-kraemer/gradle-download-task) handles the HTTP request to the GitHub URL, downloading the Zip archive of the Cedar repository main branch.
Instead of setting the integration tests path from an environment variable, the Gradle tasks extract the Cedar repository archive to the build test resources directory. This approach makes the integration test corpus available as a class path resource. Updates to the `SharedIntegrationTests` class resolve the directory from the class path location.
Additional changes include updating the …

Update Gradle build to download integration tests

---

CedarJava/README.md
CedarJava/build.gradle
CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java
CedarJava/src/main/java/com/cedarpolicy/model/slice/Policy.java

*Issue #, if available:* #95
This pull request removes direct references to SLF4J logging from all classes. The `Policy` class had an unused logger, leaving the `BasicAuthorizationEngine` class as the only runtime usage at the `TRACE` level.
It is important to note that the `com.fizzed:jne` library has a dependency on `slf4j-api`, but that could be evaluated separately.

Remove direct use of SLF4J logging

---

.github/workflows/run_cedar_java_reusable.yml
CedarJavaFFI/src/interface.rs

Run CedarJavaFFI tests in CI

---

CedarJavaFFI/src/objects.rs

update for cedar#921

---

CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationRequest.java
CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationSuccessResponse.java
CedarJava/src/main/java/com/cedarpolicy/model/PartialAuthorizationResponse.java
CedarJava/src/main/java/com/cedarpolicy/model/ValidationRequest.java
CedarJava/src/test/java/com/cedarpolicy/JSONTests.java
CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java
CedarJavaFFI/src/tests.rs

Updates to match [cedar#837](https://github.com/cedar-policy/cedar/pull/837) and fix CI.

Updates for `cedar#837`

---

CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java
CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java
CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationRequest.java
CedarJava/src/main/java/com/cedarpolicy/model/PartialAuthorizationRequest.java
CedarJava/src/main/java/com/cedarpolicy/model/slice/PolicySet.java
CedarJava/src/test/java/com/cedarpolicy/AuthTests.java
CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java
CedarJava/src/test/java/com/cedarpolicy/pbt/IntegrationTests.java
CedarJava/src/test/java/com/cedarpolicy/pbt/ParserTest.java

https://github.com/cedar-policy/cedar-java/issues/40
Removing the Slice parameter from the [isAuthorized](https://github.com/mark-creamer-amazon/cedar-java/blob/main/CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java#L52) and [isAuthorizedPartial](https://github.com/mark-creamer-amazon/cedar-java/blob/main/CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java#L68C34-L68C53) method signatures, replacing with a `Set<Entity>` and a new object `PolicySet` which mirrors Rust's [PolicySet](https://github.com/cedar-policy/cedar/blob/b68be932492c8c8038d722962a950835ad58cfcd/cedar-policy/src/api.rs#L1585) (however without the convenient helper methods currently).
We cannot get rid of the `Slice` object entirely until the …

Removing Slice parameter from authorization APIs

---

CedarJava/src/main/java/com/cedarpolicy/CedarJson.java
CedarJava/src/main/java/com/cedarpolicy/model/policy/Policy.java
CedarJava/src/main/java/com/cedarpolicy/model/policy/PolicySet.java
CedarJava/src/main/java/com/cedarpolicy/model/schema/Schema.java
CedarJava/src/main/java/com/cedarpolicy/model/slice/BasicSlice.java
CedarJava/src/main/java/com/cedarpolicy/serializer/EntitySerializer.java
CedarJava/src/main/java/com/cedarpolicy/serializer/JsonEUID.java
CedarJava/src/main/java/com/cedarpolicy/serializer/SchemaSerializer.java
CedarJava/src/test/java/com/cedarpolicy/JSONTests.java
CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java

More edits on my quest to match [cedar#1014](https://github.com/cedar-policy/cedar/pull/1014). Like #169, these are just refactoring to make the future PR smaller.
* Switched to using custom serializers for `Entity` and `Schema`
* Added some methods on `Policy` and `PolicySet`
* Removed some `@JsonSerialize`/`@JsonDeserialize`/`@JsonProperty` annotations that had no effect (aside from confusing me)
* Changed `put` to `replace` in some tests to get rid of a warning about deprecated functionality

use custom serializers for `Entity` and `Schema`

---

CedarJava/src/main/java/com/cedarpolicy/model/policy/Policy.java
CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java
CedarJavaFFI/src/interface.rs

https://github.com/cedar-policy/cedar-java/issues/171
* Adding `toJson` method that calls a new JNI method `toJsonJni` to return the JSON String for the Policy.
* Added JNI method `toJsonJni` that takes policy source, constructs a rust Policy struct and returns the Json representation.

Adding Policy toJson method

---

CedarJava/src/main/java/com/cedarpolicy/model/ValidationRequest.java

[cedar#1041](https://github.com/cedar-policy/cedar/pull/1041) uncovered a bug in #173 😱 `ValidationRequest` objects were being serialized as `{ "schema":..., "policies": ..., "policySet": ...}` where the `policies` and `policySet` values were identical. This PR gets rid of the unwanted `policySet` field.

update policy serialization

---

CedarJava/src/main/java/com/cedarpolicy/model/policy/Policy.java
CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java
CedarJava/src/test/java/com/cedarpolicy/ValidationTests.java

Fix tests for https://github.com/cedar-policy/cedar/pull/1108, which forces `Template` objects to be templates rather than static policies.

fix for cedar#1095

---

CedarJava/src/main/java/com/cedarpolicy/model/slice/Policy.java
CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java
CedarJavaFFI/src/interface.rs

https://github.com/cedar-policy/cedar-java/issues/171
Backporting changes from https://github.com/cedar-policy/cedar-java/pull/172
Tested these changes locally with the tip of cedar-java-hello-world 3.2.x
```
// permit(principal == User::"Alice", action == Action::"View_Photo", resource in Album::"Vacation");
Set<Policy> policySet = buildPolicySlice();
Policy policy = policySet.iterator().next();
System.out.println(policy.toJson());
{"effect":"permit","principal":{"op":"==","entity":{"type":"User","id":"Alice"}},"action":{"op":"==","entity":{"type":"Action","id":"View_Photo"}},"resource":{"op":"in","entity":{"type":"Album","id":"Vacation"}},"conditions":[]}
```

Adding toJson JNI method for Policy object

---

CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java
CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java
CedarJava/src/main/java/com/cedarpolicy/CedarJson.java
CedarJava/src/main/java/com/cedarpolicy/model/EntityValidationRequest.java
CedarJava/src/main/java/com/cedarpolicy/serializer/EntitySerializer.java
CedarJava/src/test/java/com/cedarpolicy/EntityValidationTests.java
CedarJava/src/test/resources/role_schema.json
CedarJavaFFI/src/interface.rs

Issue #, if available:
Description of changes:
This PR adds support for cedar-entity-validation.
Refactor Entity json serialization similar to release/4.0.x
- Add entity validation in rust
- Add entity validation in java
- Add unit test in java and rust.

Add support for cedar entities validation.

---

CedarJava/src/main/java/com/cedarpolicy/AuthorizationEngine.java
CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java
CedarJava/src/main/java/com/cedarpolicy/model/EntityValidationRequest.java
CedarJava/src/test/java/com/cedarpolicy/EntityValidationTests.java
CedarJava/src/test/resources/role_schema.json
CedarJavaFFI/src/interface.rs
CedarJavaFFI/src/tests.rs

Cherry-pick #202

---

CedarJava/src/main/java/com/cedarpolicy/model/policy/Policy.java
CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java
CedarJavaFFI/src/interface.rs

*Issue #, if available:* #222
This PR adds `Policy.fromJson` support for Java.

Add fromJson JNI method for Policy object

---

CedarJavaFFI/src/tests.rs

and also switch from owned `String` to `&str` in a function that didn't need ownership

improve a few error messages in tests

---

.github/workflows/run_cedar_java_reusable.yml
CedarJava/build.gradle
CedarJavaFFI/rust-toolchain.toml

#251 
This PR enforces `build.gradle` to use Rust 1.81, which is specified by a constant.

Use Rust 1.81 to crossbuild FFI

---

CedarJava/config/checkstyle/suppressions.xml
CedarJava/src/main/java/com/cedarpolicy/BasicAuthorizationEngine.java
CedarJava/src/main/java/com/cedarpolicy/model/PartialAuthorizationResponse.java
CedarJava/src/main/java/com/cedarpolicy/model/PartialAuthorizationSuccessResponse.java
CedarJava/src/test/java/com/cedarpolicy/AuthTests.java
CedarJava/src/test/java/com/cedarpolicy/JSONTests.java

Cherry-pick #256

---

CedarJava/src/main/java/com/cedarpolicy/serializer/ValueDeserializer.java
CedarJava/src/main/java/com/cedarpolicy/serializer/ValueSerializer.java
CedarJava/src/main/java/com/cedarpolicy/value/Unknown.java
CedarJava/src/test/java/com/cedarpolicy/AuthTests.java
CedarJava/src/test/java/com/cedarpolicy/JSONTests.java

This PR introduces support for the 'Unknown' value extension in the Cedar Java binding, specifically for use in partial authorization scenarios.

Add unknown value for cedar partial evaluation

---

CedarJava/src/main/java/com/cedarpolicy/model/Effect.java
CedarJava/src/main/java/com/cedarpolicy/model/policy/Policy.java
CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java
CedarJavaFFI/src/interface.rs

This PR adds functionality to expose the `effect` of Cedar policies, aligning with the capabilities available in Cedar Rust's [`Policy`](https://docs.rs/cedar-policy/latest/cedar_policy/struct.Policy.html#method.effect) and [`Template`](https://docs.rs/cedar-policy/latest/cedar_policy/struct.Template.html#method.effect) implementations.
- Implements `effect()` method to determine if a policy is a `"permit"` or `"forbid"` policy
- Exposes `effect` for both static policies and templates
- Adds unit tests
Cedar Java currently uses a unified `Policy` class for both static policies and templates, unlike Cedar Rust which separates these concerns into distinct `Policy` and `Template` structs. To maintain compatibility while exposing this functionality:
1. The `effect()` method first attempts to …

Exposes policy effect for static policies and templates

---

CedarJava/src/main/java/com/cedarpolicy/model/entity/Entity.java
CedarJava/src/main/java/com/cedarpolicy/model/policy/PolicySet.java
CedarJava/src/test/java/com/cedarpolicy/EntityTests.java
CedarJava/src/test/java/com/cedarpolicy/PolicySetTests.java
CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java

- Adds the following getter methods:
- Entity.getAttr [Rust_equivalent](https://docs.rs/cedar-policy/4.2.2/cedar_policy/struct.Entity.html#method.attr)
- PolicySet.getNumPolicies [Rust_equivalent](https://docs.rs/cedar-policy/4.2.2/cedar_policy/struct.PolicySet.html#method.num_of_policies)
- PolicySet.getNumTemplates [Rust_equivalent](https://docs.rs/cedar-policy/4.2.2/cedar_policy/struct.PolicySet.html#method.num_of_templates)
- Adds unit tests for the getter methods
- Adds explicit scope modifier for policyEffectTest
_Note:_ 
While fields are currently public, these getters lay groundwork for future encapsulation:
- Will enable transition of fields to private access
- Establishes consistent getter/setter pattern aligned with Cedar Rust implementation
- Preserves API compatibility …

Adds getter methods for PolicySet and Entity

---

CedarJavaFFI/Cargo.toml
CedarJavaFFI/README.md
CedarJavaFFI/src/interface.rs
CedarJavaFFI/src/jvm_test_utils.rs
CedarJavaFFI/src/lib.rs

- Currently only `fn callCedar` has direct tests in CedarJavaFFI, while other interface methods are tested indirectly via CedarJava. This leads to test coverage failures in CedarJavaFFI for some build systems
- Testing interface methods requires running a JVM instance from Rust
- This PR adds:
- A utility method to create a single immutable JVM instance for use across parallel tests
- An example test demonstrating usage of the shared JVM instance

Add JVM to enable testing of CedarJavaFFI interface methods

---

CedarJava/.gitignore
CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationRequest.java
CedarJava/src/main/java/com/cedarpolicy/model/Context.java
CedarJava/src/main/java/com/cedarpolicy/model/PartialAuthorizationRequest.java
CedarJava/src/test/java/com/cedarpolicy/AuthTests.java
CedarJava/src/test/java/com/cedarpolicy/ContextTests.java

1. Currently, CedarJava handles Context as `Map<String,Value>` without a dedicated class. This PR creates Java equivalent class for [Context](https://docs.rs/cedar-policy/latest/cedar_policy/struct.Context.html).
2. Implements methods to create and merge Contexts within CedarJava. Currently, does not implement from_* methods.
3. Uses method overloading to make it backward compatible in authorization requests.
4. Implements tests for Context. 
5. Implements tests to verify backward compatibility in AuthorizationRequest and PartialAuthorizationRequest.
_Future Consideration_:
- Create `.copy()` for all classes that implement `Value` interface. This will allow us to create deep-copy of any object that use `Value`. Currently, we can only create shallow copies for objects such as `Context`. …

Creates Backward Compatible Context Class

---

CedarJava/src/main/java/com/cedarpolicy/model/AuthorizationSuccessResponse.java
CedarJava/src/main/java/com/cedarpolicy/model/DetailedError.java

Resolves #257
1. Creates public getter methods for `AuthorizationError`
2. Overrides `.toString()` for `AuthorizationError`, `DetailedError`, and `SourceLabel`.
**Example:**
```java
Set<String> reasons = new HashSet<>();
reasons.add("p1");
List<SourceLabel> sourceLabel = List.of(new SourceLabel(Optional.of("sourceLabel"), 0, 10));
final Diagnostics diagnostics = new Diagnostics(new HashSet<>(reasons),
List.of(new AuthorizationError("policyError1",
new DetailedError("message", Optional.of("dummyHelp"), 
Optional.of("dummyCode"),
Optional.of("dummyUrl"), 
Optional.of(Severity.Error), 
Optional.of(sourceLabel),
Optional.empty()))));
final AuthorizationSuccessResponse authorizationSuccessResponse = new AuthorizationSuccessResponse(
Decision.Deny, diagnostics); …
```

Resolves #257

---

CedarJava/src/main/java/com/cedarpolicy/model/policy/Policy.java
CedarJava/src/test/java/com/cedarpolicy/PolicyTests.java
CedarJavaFFI/src/interface.rs
CedarJavaFFI/src/jmap.rs
CedarJavaFFI/src/lib.rs

This PR implements annotation getters for the `Policy` class, providing access to both static policy and template policy annotations.
- Implements a Java HashMap in `CedarJavaFFI` for annotation management and JNI communication
- Adds annotation access methods to `Policy` class:
- `getAnnotation(String key)`
- `getAnnotations()`
- Implements lazy loading pattern for annotations:
- Annotations initialize via JNI only on first getter call
- Subsequent calls utilize cached annotations
- Adds test coverage for:
- New FFI methods
- `CedarJavaFFI` HashMap implementation
- `Policy` annotation getters
1. Handling Static Policies and Templates
- Uses try-catch approach to attempt static policy annotation retrieval first
- Falls back to template annotation retrieval on failure …

Adds annotation support for Policy

---

CedarJava/CHANGELOG.md
README.md

1. Refines README.md
1. Adds instructions to import `CedarJava` from maven
2. Adds a mini-example
3. Adds links to CedarJava examples in `cedar-policy/cedar-examples`
2. Updates CHANGELOG for upcoming release items

Refines documentation

---

.github/workflows/ci.yml
CedarJava/CHANGELOG.md
CedarJava/build.gradle
CedarJavaFFI/Cargo.toml

1. Bumps version number in CHANGELOG.MD to **4.3.0**
2. Bumps version number in `CedarJava/build.gradle` to **4.3.0**
3. Updates `CedarJavaFFI/Cargo.toml`:
1. Bumps version number for `CedarJavaFFI` to **4.3.0**
2. Bumps `cedar-policy `dependency version to **4.3.3** and sets its branch to `release/4.3.x`
3. Bumps `cedar-policy-formatter` dependency version to **4.3.3** and sets its branch to `release/4.3.x`
4. Updates Github CI workflow to use `release/4.3.x` branch for `cedar-policy`

Creates Release 4.3.x

---

CedarJava/CHANGELOG.md
CedarJava/build.gradle

This PR adds explicit Zig version (0.11) validation during the publishing process to ensure consistent artifact compatibility. 
**Changes:**
- Adds version check during package publishing
- Does not enforce version check during normal build processes
**Rationale:**
Without version validation, artifacts could be published using different Zig versions, causing compatibility issues. By validating only during publishing, we ensure consistent releases while allowing developers to build from source using their preferred Zig version.
1. Running `validateZigVersion` task with incorrect Zig Version:
```
$> gradle validateZigVersion
> Task :validateZigVersion FAILED
Detected Zig version: 0.13.0
[Incubating] Problems report is available at: …
```

Adds Zig version validation for publishing task

---

CedarJava/CHANGELOG.md
CedarJava/build.gradle
CedarJavaFFI/Cargo.toml

Cherry-picks #306 for Zig version validation and bumps version numbers for the patch release.

Cherry-picks #306

---

CedarJava/src/test/java/com/cedarpolicy/EntitiesTests.java

* Adds `JSONException` for tests using `JSONAssert` to make it compatible with older versions of `JSONAssert`
* Does not affect any APIs or functionality

updates tests to be compatible with older JSONAssert versions

---

CedarJavaFFI/src/interface.rs
CedarJavaFFI/src/jlist.rs
CedarJavaFFI/src/jset.rs

Tests for non refactored methods along with some tests cases I had written for JLIST.RS over the weekend.

adds FFI Tests 

---

CedarJava/src/main/java/com/cedarpolicy/model/schema/Schema.java
CedarJava/src/test/java/com/cedarpolicy/SchemaTests.java
CedarJavaFFI/src/interface.rs

This PR introduces new functionality for schema format conversion:
1. Adds two new conversion methods:
- `.toCedarFormat()`: Converts and returns Schema in Cedar format
- `.toJsonFormat()`: Converts and returns Schema in JSON format
2. Implements comprehensive test coverage:
- FFI layer tests to verify native interactions
- Java unit tests to ensure proper format conversions
Resolves #181 action item for schema conversion

adds schema conversion APIs

---

CedarJava/CHANGELOG.md
CedarJava/src/main/java/com/cedarpolicy/serializer/ValueDeserializer.java
CedarJava/src/main/java/com/cedarpolicy/serializer/ValueSerializer.java
CedarJava/src/main/java/com/cedarpolicy/value/DateTime.java
CedarJava/src/test/java/com/cedarpolicy/DateTimeTests.java
CedarJava/src/test/java/com/cedarpolicy/pbt/IntegrationTests.java

Adds DateTime Extension Support ([RFC 80](https://github.com/strongdm/cedar-rfcs/blob/datetime-rfc/text/0080-datetime-extension.md))
- Implements new `com.cedarpolicy.value.DateTime` class
- Validates input dates against supported format specifications
- Stores `DateTime` value in `String` representation
- Integrates `DateTime` support in serialization layer
- Extends `ValueSerializer` to handle `DateTime` serialization
- Adds `DateTime` deserialization support in `ValueDeserializer`
- Testing
- Adds unit tests covering `DateTime` validation, serialization, and edge cases
- Includes integration tests to verify end-to-end `DateTime` functionality
- Updates CHANGELOG
```java
Set<Entity> entities = new HashSet<>();
String principalId = "alice";
Map<String, Value> principalAttributes = new …
```

Adds DateTime Extension Support

---

CedarJava/src/main/java/com/cedarpolicy/model/policy/PolicySet.java
CedarJava/src/test/java/com/cedarpolicy/JSONTests.java
CedarJava/src/test/java/com/cedarpolicy/PolicySetTests.java
CedarJava/src/test/java/com/cedarpolicy/TestUtil.java
CedarJavaFFI/src/interface.rs
CedarJavaFFI/src/jlist.rs

Implements JSON conversion support for CedarJava, allowing PolicySet objects to be converted to Cedar's JSON format, similar to the `to_json()` functionality in the [cedar_policy Rust library](https://docs.rs/cedar-policy/latest/cedar_policy/struct.PolicySet.html#method.to_json).
- Adds `.toJson` method for `PolicySet` to convert PolicySet to Cedar JSON format 
- Adds tests for both Java and FFI
- Improves test output clarity by adding `env.exception_clear().unwrap()`
```java
EntityTypeName principalType = EntityTypeName.parse("User").get();
Set<Policy> policies = new HashSet<>();
Set<Policy> templates = new HashSet<>();
ArrayList<TemplateLink> templateLinks = new ArrayList<TemplateLink>();
ArrayList<LinkValue> linkValueList = new ArrayList<>();
String fullPolicy =
"permit(principal == …
```

adds PolicySet to JSON conversion

---

CedarJava/build.gradle
CedarJava/src/main/java/com/cedarpolicy/serializer/ValueDeserializer.java
CedarJava/src/main/java/com/cedarpolicy/serializer/ValueSerializer.java
CedarJava/src/main/java/com/cedarpolicy/value/Decimal.java
CedarJava/src/main/java/com/cedarpolicy/value/Duration.java
CedarJava/src/main/java/com/cedarpolicy/value/IpAddress.java
CedarJava/src/main/java/com/cedarpolicy/value/functions/Offset.java
CedarJava/src/test/java/com/cedarpolicy/DurationTests.java
CedarJava/src/test/java/com/cedarpolicy/OffsetTests.java
CedarJava/src/test/java/com/cedarpolicy/SharedIntegrationTests.java
CedarJava/src/test/java/com/cedarpolicy/pbt/IntegrationTests.java

- Adds Duration extension and Offset functions ([RFC 80](https://github.com/strongdm/cedar-rfcs/blob/datetime-rfc/text/0080-datetime-extension.md))
- Adds missing support for negative decimal and CIDR suffixes '
* Implements `com.cedarpolicy.value.Duration` 
* Validates input against supported format specifications
* Converts and stores it in millisecond format for semantic comparison
* Adds JSON Serializer and Deserializer support
* Adds unit and integration tests
* Implements `com.cedarpolicy.value.functions.Offset`
* Adds JSON Serializer and Deserializer support
* Does not implement `equals` or `hash` as this is supposed to represent a function
* Adds unit and integration tests
* Bug Fixes (Cause for previously failing shared integration corpus tests)
* Adds support negative decimals …

Adds Duration Extension and Offset Function support

---

.github/workflows/run_cedar_java_reusable.yml

N/A
Added missing rust toolchain component to GHA workflow.

Added missing rust toolchain component to GHA workflow
